### ISSUE TITLE
Source code jni

### ISSUE THREAD

**Issue by nguyendinhduc** [CoXier/LowPoly#1]
Can you give me source code jni?

**Comment by drakeet** [comment]
+1
The project is pretty cool! Thank you for your share. But Native code is not open source, what a pity.

**Comment by wu-leaf** [comment]
+1
what a pity

**Comment by CoXier** [comment]
Thanks! Since the algo can be better . So I want to improve it and then open it

**Comment by junyuecao** [comment]
+1 
What a pity.
