### ISSUE TITLE
Native module source

### ISSUE THREAD

**Issue by FabianTerhorst** [CoXier/LowPoly#3]
Can you provide the source code of the native module?

**Comment by andyxialm** [comment]
+1

**Comment by leconio** [comment]
pls +1

**Comment by JesusM** [comment]
Correct me if I'm wrong, but this way we could also target architectures that are not covered by the `.so` provided in this repo (i.e., x86_64)

**Comment by CoXier** [comment]
@JesusM You can set options in ndk an you can target all architectures
