### ISSUE TITLE
 java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by viphsx123** [CoXier/LowPoly#5]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "srand" referenced by "liblowpoly.so"...

**Comment by CoXier** [comment]
which way?Import module or add it as a dependency?

**Comment by abhriyaroy** [comment]
same error.
dependency way.

**Comment by CoXier** [comment]
I  have tested serval new projects , however I have not gotten this error.I am sorry

**Comment by royabh1** [comment]
![low poly error](https://cloud.githubusercontent.com/assets/20481602/19122342/a41baae4-8b47-11e6-8e0c-a4e8a8e94693.png)

It is a legit problem. Please check.
