### ISSUE TITLE
Cannot locate symbol "srand" referenced by "liblowpoly.so"

### ISSUE THREAD

**Issue by drakeet** [CoXier/LowPoly#7]
``` java
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "srand" referenced by "liblowpoly.so"...
    at java.lang.Runtime.loadLibrary(Runtime.java:364)
    at java.lang.System.loadLibrary(System.java:526)
    at com.uniquestudio.lowpoly.LowPoly.<clinit>(SourceFile:14)
```

**Comment by drakeet** [comment]
It occurred on some low-end systems:

![image](https://cloud.githubusercontent.com/assets/5214214/19236678/2ea523f2-8f2b-11e6-94e5-7208a0fa5192.png)

**Comment by drakeet** [comment]
May be the issue will be helpful: https://github.com/cocos2d/cocos2d-x/issues/14034

**Comment by drakeet** [comment]
And this: https://github.com/cocos2d/cocos2d-x/pull/16079/files

**Comment by CoXier** [comment]
I have fixed it.Please check
